bq-dbt-workshop:
  outputs:
    dev:
      dataset: trips_data_all
      fixed_retries: 1
      keyfile: ~/.google/credentials/google_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: inspired-victor-409616
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
